# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build-test:

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish-release:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Publish Release
        run: |
          dotnet publish Tic-Tac-Toe/Tic-Tac-Toe.csproj --configuration Debug --output ./publish --self-contained false --framework net9.0
      - name: Create README.txt
        run: |
          echo "Привет! Чтобы запустить игру, установите .NET 9.0 Runtime" > ./publish/README.txt
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TicTacToe-Release-build-${{ matrix.os }}
          path: ./publish
